# Generated by Django 2.2 on 2020-11-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
