# Generated by Django 2.2 on 2020-11-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webprofiles', '0002_auto_20201104_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
