# Generated by Django 2.2 on 2020-11-04 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webprofiles', '0003_auto_20201104_2224'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofiles',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='user_permissions',
        ),
    ]
