# Generated by Django 2.2 on 2020-11-05 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webprofiles', '0004_auto_20201104_2228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfiles',
            new_name='EmployeeProfiles',
        ),
    ]
